### ISSUE TITLE
Инструмент framework-k1921vk-sdk недоступен для вашей операционной системы.

### ISSUE THREAD

**Issue by MrFermer** [DCVostok/vostok-arduinoide-board-manager#2]
Аналог [данной проблемы](https://github.com/DCVostok/vostok-arduinoide-board-manager/issues/1#issue-1573871326).

ОС: Manjaro-ARM Linux 22.12
Архитектура: aarch64

Отсутствует описание архитектуры aarch64. Проблема решается добавлением кода:

> {
>               "host": "aarch64-linux-gnu",
>               "url": "https://github.com/DCVostok/framework-k1921vk-sdk/archive/refs/tags/v1.7.3.zip",
>               "archiveFileName": "framework-k1921vk-sdk-1.7.3.zip",
>               "checksum": "SHA-256:0c9341d7b7c8459338fa5783aa530b8accecae19fa3f7299a80a1205832215d0",
>               "size": "1882225"
>             },

в секцию

> "tools": [
> <...>
> {
>           "name": "framework-k1921vk-sdk",
>           "version": "1.7.3",
>           "systems": [

Прошу добавить данный код в файл package_vostok_index.json

**Comment by MrFermer** [comment]
Могу попробовать сделать pull request файла, с которым установка платы в "Arduino IDE" прошла успешно. Однако, у меня нет опыта в этом.

**Comment by kenny5660** [comment]
Хорошо, сейчас добавлю эту архитектуру
